-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 17:45:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`carritocompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carritocompras` (
  `id_producto` VARCHAR(25) NOT NULL,
  `confirmarpedido` VARCHAR(10) NULL DEFAULT NULL,
  `eliminarproducto` VARCHAR(10) NULL DEFAULT NULL,
  `preciototal` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_referencia` VARCHAR(25) NOT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `color` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_referencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`agregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agregado` (
  `Producto_id_refrencia` VARCHAR(25) NOT NULL,
  `Carritocompras_id_producto` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Producto_id_refrencia`, `Carritocompras_id_producto`),
  INDEX `fk_Producto_has_Carritocompras_Carritocompras1_idx` (`Carritocompras_id_producto` ASC) VISIBLE,
  INDEX `fk_Producto_has_Carritocompras_Producto1_idx` (`Producto_id_refrencia` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Carritocompras_Carritocompras1`
    FOREIGN KEY (`Carritocompras_id_producto`)
    REFERENCES `mydb`.`carritocompras` (`id_producto`),
  CONSTRAINT `fk_Producto_has_Carritocompras_Producto1`
    FOREIGN KEY (`Producto_id_refrencia`)
    REFERENCES `mydb`.`producto` (`id_referencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `no_cliente` VARCHAR(45) NOT NULL,
  `no_factura` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`no_cliente`),
  UNIQUE INDEX `UKqvpk5ac10iu119ky2mj8362de` (`no_factura` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuenta` (
  `id_titular` VARCHAR(25) NOT NULL,
  `fechacreacion` DATE NULL DEFAULT NULL,
  `mediospago` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_titular`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `id_empleado` VARCHAR(25) NOT NULL,
  `cargo` VARCHAR(50) NULL DEFAULT NULL,
  `sueldo` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `identificacion` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `direccion` VARCHAR(25) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  `cliente_no_factura` VARCHAR(25) NULL DEFAULT NULL,
  `cuenta_id_titular` VARCHAR(25) NULL DEFAULT NULL,
  `empleado_id_empleado` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`identificacion`),
  INDEX `FK31dlko1hb8y2cynmpnep8nqqg` (`cliente_no_factura` ASC) VISIBLE,
  INDEX `FKfbp0j1r7hjpdvakp1fjv0qlxi` (`cuenta_id_titular` ASC) VISIBLE,
  INDEX `FKr8dhmrcs7s2w9dkt8ci3qnt9m` (`empleado_id_empleado` ASC) VISIBLE,
  CONSTRAINT `FK31dlko1hb8y2cynmpnep8nqqg`
    FOREIGN KEY (`cliente_no_factura`)
    REFERENCES `mydb`.`cliente` (`no_factura`),
  CONSTRAINT `FKfbp0j1r7hjpdvakp1fjv0qlxi`
    FOREIGN KEY (`cuenta_id_titular`)
    REFERENCES `mydb`.`cuenta` (`id_titular`),
  CONSTRAINT `FKr8dhmrcs7s2w9dkt8ci3qnt9m`
    FOREIGN KEY (`empleado_id_empleado`)
    REFERENCES `mydb`.`empleado` (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`busca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`busca` (
  `Persona_identificacion` VARCHAR(25) NOT NULL,
  `Producto_id_refrencia` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Persona_identificacion`, `Producto_id_refrencia`),
  INDEX `fk_Persona_has_Producto_Producto1_idx` (`Producto_id_refrencia` ASC) VISIBLE,
  INDEX `fk_Persona_has_Producto_Persona1_idx` (`Persona_identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_has_Producto_Persona1`
    FOREIGN KEY (`Persona_identificacion`)
    REFERENCES `mydb`.`persona` (`identificacion`),
  CONSTRAINT `fk_Persona_has_Producto_Producto1`
    FOREIGN KEY (`Producto_id_refrencia`)
    REFERENCES `mydb`.`producto` (`id_referencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`comprar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comprar` (
  `Carritocompras_id_producto` VARCHAR(25) NOT NULL,
  `Cuenta_id_titular` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Carritocompras_id_producto`, `Cuenta_id_titular`),
  INDEX `fk_Carritocompras_has_Cuenta_Cuenta1_idx` (`Cuenta_id_titular` ASC) VISIBLE,
  INDEX `fk_Carritocompras_has_Cuenta_Carritocompras1_idx` (`Carritocompras_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_Carritocompras_has_Cuenta_Carritocompras1`
    FOREIGN KEY (`Carritocompras_id_producto`)
    REFERENCES `mydb`.`carritocompras` (`id_producto`),
  CONSTRAINT `fk_Carritocompras_has_Cuenta_Cuenta1`
    FOREIGN KEY (`Cuenta_id_titular`)
    REFERENCES `mydb`.`cuenta` (`id_titular`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
