-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 18:22:02 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `id_titular` VARCHAR(25) NOT NULL,
  `fechacreacion` DATE NULL,
  `mediospago` TEXT(50) NULL,
  PRIMARY KEY (`id_titular`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `id_Empleado` VARCHAR(25) NOT NULL,
  `cargo` TEXT(50) NULL,
  `sueldo` FLOAT NULL,
  PRIMARY KEY (`id_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `no_factura` VARCHAR(25) NOT NULL,
  `no_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`no_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `identificacion` VARCHAR(25) NOT NULL,
  `nombre` TEXT(50) NULL,
  `apellidos` TEXT(50) NULL,
  `direccion` VARCHAR(25) NULL,
  `telefono` VARCHAR(25) NULL,
  `Cuenta_id_titular` VARCHAR(25) NULL,
  `Empleado_id_Empleado` VARCHAR(25) NULL,
  `Cliente_no_factura` VARCHAR(25) NULL,
  PRIMARY KEY (`identificacion`),
  INDEX `fk_Persona_Cuenta_idx` (`Cuenta_id_titular` ASC) VISIBLE,
  INDEX `fk_Persona_Empleado1_idx` (`Empleado_id_Empleado` ASC) VISIBLE,
  INDEX `fk_Persona_Cliente1_idx` (`Cliente_no_factura` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Cuenta`
    FOREIGN KEY (`Cuenta_id_titular`)
    REFERENCES `mydb`.`Cuenta` (`id_titular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Empleado1`
    FOREIGN KEY (`Empleado_id_Empleado`)
    REFERENCES `mydb`.`Empleado` (`id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Cliente1`
    FOREIGN KEY (`Cliente_no_factura`)
    REFERENCES `mydb`.`Cliente` (`no_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `id_referencia` VARCHAR(25) NOT NULL,
  `nombre` TEXT(50) NULL,
  `categoria` TEXT(50) NULL,
  `color` TEXT(50) NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`id_referencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Busca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Busca` (
  `Persona_identificacion` VARCHAR(25) NOT NULL,
  `Producto_id_refrencia` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Persona_identificacion`, `Producto_id_refrencia`),
  INDEX `fk_Persona_has_Producto_Producto1_idx` (`Producto_id_refrencia` ASC) VISIBLE,
  INDEX `fk_Persona_has_Producto_Persona1_idx` (`Persona_identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_has_Producto_Persona1`
    FOREIGN KEY (`Persona_identificacion`)
    REFERENCES `mydb`.`Persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Producto_Producto1`
    FOREIGN KEY (`Producto_id_refrencia`)
    REFERENCES `mydb`.`Producto` (`id_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carritocompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carritocompras` (
  `id_producto` VARCHAR(25) NOT NULL,
  `eliminarproducto` TEXT(10) NULL,
  `confirmarpedido` TEXT(10) NULL,
  `preciototal` FLOAT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agregado` (
  `Producto_id_refrencia` VARCHAR(25) NOT NULL,
  `Carritocompras_id_producto` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Producto_id_refrencia`, `Carritocompras_id_producto`),
  INDEX `fk_Producto_has_Carritocompras_Carritocompras1_idx` (`Carritocompras_id_producto` ASC) VISIBLE,
  INDEX `fk_Producto_has_Carritocompras_Producto1_idx` (`Producto_id_refrencia` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Carritocompras_Producto1`
    FOREIGN KEY (`Producto_id_refrencia`)
    REFERENCES `mydb`.`Producto` (`id_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Carritocompras_Carritocompras1`
    FOREIGN KEY (`Carritocompras_id_producto`)
    REFERENCES `mydb`.`Carritocompras` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comprar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comprar` (
  `Carritocompras_id_producto` VARCHAR(25) NOT NULL,
  `Cuenta_id_titular` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Carritocompras_id_producto`, `Cuenta_id_titular`),
  INDEX `fk_Carritocompras_has_Cuenta_Cuenta1_idx` (`Cuenta_id_titular` ASC) VISIBLE,
  INDEX `fk_Carritocompras_has_Cuenta_Carritocompras1_idx` (`Carritocompras_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_Carritocompras_has_Cuenta_Carritocompras1`
    FOREIGN KEY (`Carritocompras_id_producto`)
    REFERENCES `mydb`.`Carritocompras` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carritocompras_has_Cuenta_Cuenta1`
    FOREIGN KEY (`Cuenta_id_titular`)
    REFERENCES `mydb`.`Cuenta` (`id_titular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
